### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/bootstrap-colorpicker ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by itsjavi** [comment]
Thank you @monkeywithacupcake !

Just one thing, can you remove the npm dependency? It looks a bit weird to me to have `opencollective` as a dependency to only display a message after install. I think I can do that with a postinstall script just printing a message :) 
Thank you

Ps: I have problems logging in because Open Collective has linked my account to a Github no-reply email when I connected Github. I don't know how to solve this but I asked in Slack in the `#support` channel.

**Comment by itsjavi** [comment]
It's ok I can change that now that I have time. Thank you

**Comment by itsjavi** [comment]
@monkeywithacupcake I may still need help because the contributors SVG seems broken
https://github.com/farbelous/bootstrap-colorpicker#contributors

**Comment by monkeywithacupcake** [comment]
Yay! You got it working.

**Pull request merged**
