### PR TITLE
Disable and enable colorpicker also without input element.

### PR DESCRIPTION
**Pull request by jetic83**
solves issue #224

### CODE REVIEW

**Comment by githubSathishkumar** [comment]
When this change(next version) will release or is live? We cannot use color-picker without this change. @jetic83

**Comment by githubSathishkumar** [comment]
^ @itsjavi When will be the next version release?

**Comment by itsjavi** [comment]
it is live since v2.5.2 @githubSathishkumar please check commit history

**Comment by githubSathishkumar** [comment]
@itsjavi Seems like release notes for v2.5.2 is not updated. Kindly update release notes.

**Pull request merged**
