### PR TITLE
V3

### PR DESCRIPTION
**Pull request by skullwritter**
### Description

{Please write here}

### Check list

Please fill this check list before submitting a pull request:

- [ ] The build process has been run (`npm run build`) and does not contain any errors.
- [ ] All tests are green after running `npm run test`.
- [ ] New tests have been added or modified for the introduced changes.
- [ ] New examples have been added for the newly introduced features.
- [ ] All the examples are still working as expected compared to the [official website](https://farbelous.io/bootstrap-colorpicker).
- [ ] This PR follows all other [`CONTRIBUTING.md`](.github/CONTRIBUTING.md#pull-requests) guidelines for Pull Requests.

### CODE REVIEW

**Comment by itsjavi** [comment]
🤔

**Comment by skullwritter** [comment]
@itsjavi i was mergin my fork branch from v3 to master since i've included the dist files

**Comment by skullwritter** [comment]
@itsjavi also u can put the files online using: https://cdn.jsdelivr.net/gh/farbelous/bootstrap-colorpicker/

**Comment by itsjavi** [comment]
ah ok. the dist files are distributed via npm already.
there is also a zip in the releases tab here (in last release).
but thanks.

**Pull request closed without merging**
